# Generated by Django 2.2.4 on 2020-11-18 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucceededUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype', models.CharField(max_length=50, verbose_name='服务类型')),
                ('timeat', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='成功时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTop', to='userApp.User', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '已成功案例',
                'verbose_name_plural': '已成功案例',
                'ordering': ('-timeat',),
            },
        ),
    ]
