# Generated by Django 2.2.4 on 2020-11-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='succeededuser',
            options={'ordering': ('-timeat',), 'verbose_name': '最新成交', 'verbose_name_plural': '最新成交'},
        ),
        migrations.RemoveField(
            model_name='succeededuser',
            name='servicetype',
        ),
        migrations.AlterField(
            model_name='succeededuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTop', to='userApp.User', verbose_name='用户'),
        ),
    ]
