# Generated by Django 2.2.4 on 2020-11-25 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20201124_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32),
        ),
    ]
