# Generated by Django 2.2.4 on 2020-11-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20201125_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='c_time',
        ),
    ]
