# Generated by Django 2.2.4 on 2020-11-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_remove_user_c_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headsculpture',
            field=models.ImageField(default='headsculpture/chicken.jpeg', upload_to='headsculpture/', verbose_name='头像'),
        ),
    ]
