# Generated by Django 2.2.4 on 2020-12-03 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0007_auto_20201203_2224'),
        ('userApp', '0006_auto_20201125_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '支付未成功'), (3, '运行中'), (4, '已取消'), (5, '已成功占座'), (6, '占座失败')], default=1)),
                ('trade_no', models.CharField(default='', max_length=128, verbose_name='支付编号')),
                ('start_time', models.DateTimeField(auto_now=True, max_length=20, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='结束时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.Product', verbose_name='金额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
