# Generated by Django 2.2.4 on 2020-11-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('yzw', '中国研究生招生信息网'), ('amac', '基金从业人员资格考试')], max_length=50, verbose_name='服务名称')),
                ('website', models.URLField(verbose_name='网址')),
                ('warninfo', models.TextField(default='暂无注意事项', verbose_name='使用注意')),
                ('productType', models.CharField(choices=[('学历类考试', '学历类考试'), ('计算机类考试', '计算机类考试'), ('金融类考试', '金融类考试'), ('语言类考试', '语言类考试')], max_length=50, verbose_name='服务类型')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='价格')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='product/', verbose_name='成功截图')),
                ('product', models.ForeignKey(on_delete='models.CASCADE', related_name='productImgs', to='productApp.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '成功截图',
                'verbose_name_plural': '成功截图',
            },
        ),
    ]
