# Generated by Django 2.2.4 on 2020-11-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_auto_20201119_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageCover',
            field=models.ImageField(blank=True, upload_to='product_cover/', verbose_name='产品封面'),
        ),
    ]
