# Generated by Django 2.2.4 on 2020-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_product_imagecover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='textModel',
            field=models.TextField(choices=[('yzw', '\n        # 请替换双引号的内的相应内容\n        SFZ = "532225199810140369" # 身份证/手机号\n        DLMM = "421519" # 登陆密码\n        BKSF = "江苏省" # 报考省份\n        BKXX = "南京航空航天大学" # 报考学校\n        KSFS = "全国统一考试" # 考试方式\n        ZXJH = "无" # 专项计划\n        BKLB = "非定向就业" # 报考类别\n        BKYX = "自动化学院" # 报考院系\n        BKZY = "电子信息" # 报考专业\n        YJFX = "控制系统应用工程" # 研究方向\n        XXFS = "全日制" # 学习方式\n        KSKM = "(101)思想政治理论" # 考试科目\n        BKDSF = "湖南省" # 报考点省份\n        BKDXX = "湖南科技大学" # 报考点学校\n        SJR = "1007307796@qq.com" # 收件人,目前只支持QQ邮箱 \n        '), ('amac', '\n        # 请替换双引号的内的相应内容\n        YHM = "620102200010211128" # 身份证/手机号\n        DLMM = "319379yy" # 登陆密码\n        DQDM1 = \'3\' # 地区代码1\n        DQDM2 = \'3526\' # 地区代码2\n        DQDM3 = \'1131\' # 地区代码3\n        SJR = "1007307796@qq.com" # 收件人,目前只支持QQ邮箱\n        ')], default='', verbose_name='模板'),
        ),
    ]
