# Generated by Django 2.2.4 on 2020-12-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_auto_20201202_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='textModel',
            field=models.TextField(choices=[('yzw', '\n        # YZW\\\n        # 请替换双引号的内的相应内容\\\n        SFZ = "532225199810140369" # 身份证/手机号\\\n\n        DLMM = "421519" # 登陆密码\\\n\n        BKSF = "江苏省" # 报考省份\\\n\n        BKXX = "南京航空航天大学" # 报考学校\\\n\n        KSFS = "全国统一考试" # 考试方式\\\n\n        ZXJH = "无" # 专项计划\\\n\n        BKLB = "非定向就业" # 报考类别\\\n\n        BKYX = "自动化学院" # 报考院系\\\n\n        BKZY = "电子信息" # 报考专业 <em>请注意区分专硕与学硕</em>\\\n\n        YJFX = "控制系统应用工程" # 研究方向\\\n\n        XXFS = "全日制" # 学习方式\\\n\n        KSKM = "(101)思想政治理论" # 考试科目 <em>若研招网下拉框有多条数据，请输入区别于其他考试科目的具体科目名称</em>\\\n\n        BKDSF = "湖南省" # 报考点省份\\\n\n        BKDXX = "湖南科技大学" # 报考点学校\\\n\n        SJR = "1007307796@qq.com" # 收件人,目前只支持QQ邮箱 <em>若不填写，则由客服微信消息通知</em>\\\n        '), ('amac', '\n        # AMAC\n        # 请替换双引号的内的相应内容\\\n\n        YHM = "620102200010211128" # 身份证/手机号\\\n\n        DLMM = "319379yy" # 登陆密码\\\n\n        DQDM1 = \'3\' # 地区代码1\\\n\n        DQDM2 = \'3526\' # 地区代码2\\\n\n        DQDM3 = \'1131\' # 地区代码3\\\n\n        SJR = "1007307796@qq.com" # 收件人,目前只支持QQ邮箱 <em>若不填写，则由客服微信消息通知</em>        ')], default='', verbose_name='模板'),
        ),
    ]
