# Generated by Django 2.2.4 on 2020-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_auto_20201202_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.PositiveIntegerField(default=0, verbose_name='成交量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='textModel',
            field=models.TextField(choices=[('yzw', '\n# YZW\n# 请替换双引号的内的相应内容\nSFZ = "532225199810140369" # 身份证/手机号\nDLMM = "421519" # 登陆密码\nBKSF = "江苏省" # 报考省份\nBKXX = "南京航空航天大学" # 报考学校\nKSFS = "全国统一考试" # 考试方式\nZXJH = "无" # 专项计划\nBKLB = "非定向就业" # 报考类别\nBKYX = "自动化学院" # 报考院系\n# !请注意区分专硕与学硕\nBKZY = "电子信息" # 报考专业\nYJFX = "控制系统应用工程" # 研究方向\nXXFS = "全日制" # 学习方式\n# !若研招网下拉框有多条数据，请输入区别于其他考试科目的具体科目名称\nKSKM = "(101)思想政治理论" # 考试科目\nBKDSF = "湖南省" # 报考点省份\nBKDXX = "湖南科技大学" # 报考点学校\n# !若不填写，则由客服微信消息通知\nSJR = "1007307796@qq.com" # 收件人,目前只支持QQ邮箱\n        '), ('amac', '\n# AMAC\n# 请替换双引号的内的相应内容\nYHM = "620102200010211128" # 身份证/手机号\nDLMM = "319379yy" # 登陆密码\nDQDM1 = \'3\' # 地区代码1\nDQDM2 = \'3526\' # 地区代码2\nDQDM3 = \'1131\' # 地区代码3\n# !若不填写，则由客服微信消息通知\nSJR = "1007307796@qq.com" # 收件人,目前只支持QQ邮箱 \n        ')], default='', verbose_name='模板'),
        ),
    ]
